### PR TITLE
Add zig build system

### PR DESCRIPTION
**Pull request by desttinghim**
I've ported the C examples to Zig and wrote a `build.zig` to allow zig code to depend directly on webui (see examples). The URLs in the zig example code's `build.zig.zon` should be updated to point at the main repository but we have to know a commit hash with the `build.zig` available before that can be done.

### CODE REVIEW

**Comment by AlbertShown** [comment]
Thank you, @desttinghim, for your contribution.
The commit hash is `58a1da7`. I am looking forward to new _Zig_ updates.
Also, I will add _Zig_ to the list of supported languages in future WebUI commits.

**Comment by AlbertShown** [comment]
A quick test using Zig `0.11.0-dev.2196+bc0f24691`

**C:\ ... \webui\examples\Zig\hello_world>zig build-exe build.zig**
```
C:\...\webui\examples\Zig\hello_world>zig build-exe build.zig

C:\Zig\lib\std\start.zig:602:45: error: root struct of file 'build' has no member named 'main'
    switch (@typeInfo(@typeInfo(@TypeOf(root.main)).Fn.return_type.?)) {
                                        ~~~~^~~~~
C:\Zig\lib\std\start.zig:551:12: note: called from here
    return @call(.always_inline, callMain, .{});
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
C:\Zig\lib\std\start.zig:387:65: note: called from here
    std.os.windows.kernel32.ExitProcess(initEventLoopAndCallMain());
                                        ~~~~~~~~~~~~~~~~~~~~~~~~^~
```

**Comment by desttinghim** [comment]
Hey,

The command to run is `zig build`. In the root directory this will build a `libwebui.a` and install it into a generated `zig-out` directory (the include files will be installed there too). For the zig examples, cd to the directories and run `zig build run` to build + run them.

**Comment by AlbertShown** [comment]
I test it again using your instructions, and it's working fine. Thank you for providing the WebUI-Zig implementation.

I have some suggestions that will improve the UX.

1. Moving `build.zig` from the root folder to the build folder. We create one for Windows in `webui/build/Windows/Zig/build.zig`, and another for Linux in `webui/build/Linux/Zig/build.zig`. The `build.zig` files content can be identical (_Using `if target.isXXX()`_), Or it can be different based on the OS's needs.
2. The command `zig build run` should provide a Windows GUI executable instead of a Windows Console executable by adding `-mwindows`.
3. Creating a readme file in `examples/Zig/README.md`

If those steps don't cause any issues, I can apply them in the next commit.

**Comment by AlbertShown** [comment]
Hi @desttinghim, the [WebUI v2.2.0](https://github.com/alifcommunity/webui/tree/WebUI_v2.2.0) is almost finished. It's smaller and more optimized for wrapper creation.
We want to make this repo more `C` as possible. And we will move the Python, Rust, Go and TS to a separate repo soon.

Would you like please to create a new repo in `https://github.com/desttinghim/webui` and make it independent (_not a fork_) like [V WebUI](https://github.com/malisipi/vwebui) or [Nim WebUI](https://github.com/neroist/webui)?

You can add the [pre-built WebUI binaries](https://github.com/alifcommunity/webui/tree/WebUI_v2.2.0/Release) to your repo and use it directly. Or clone the WebUI repo and [build from the source](https://github.com/alifcommunity/webui/tree/WebUI_v2.2.0/build).

I will merge v2.2.0 to the main branches once you finish.

**Comment by desttinghim** [comment]
I don't have time at the moment but maybe this weekend. I don't think there is any reason to hold off on merging the v2.2.0 changes on account of the zig package.

**Comment by AlbertShown** [comment]
> I don't have time at the moment but maybe this weekend.

Understood. Please kindly create an empty repo for now in `https://github.com/desttinghim/webui`, so we can point the Zig wrapper to it in our `readme`. And, of course, you can implement the wrapper code whenever you have free time 👍

> I don't think there is any reason to hold off on merging the v2.2.0 changes on account of the zig package.

Actually, you are right. Since yesterday's [commit](https://github.com/alifcommunity/webui/commit/527d000b45fadf5fa5f81682a9816573abbc3e1b), WebUI v2.2.0 has become ready to merge. We will do it today.

**Pull request merged**
